import datetime, time, calendar
#2 a)
d = datetime.date(1997, 1, 17)
print(d)
#b) 
print(d.year)
#c)
print(d.month)
#d)
print(d.day)
#e)
list1 = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
print(d.isoweekday(), "->", list1[d.isoweekday()])
#f)
next_bday = datetime.date(2020, 1, 17)
print(next_bday - datetime.date.today())
#3)
cal = calendar.month(2017, 5)
print("Calendar for May, 2017: \n", cal)
#4)
yest = datetime.date.today() - datetime.timedelta(days=1)
print("Yesturday:", yest)
#4 a)
print(yest + datetime.timedelta(days=2))
#4 b)
print(yest - datetime.timedelta(days=3))