import datetime, time, calendar
from datetime import datetime, timedelta
weekDays = ("Monday", "Tuesday", "Wednesday", "Tuesday", "Friday", "Saturday", "Sunday")
#2  a)
current_time = datetime.now() 
print(current_time)
#b)
localTime = time.localtime()
print("Year:", localTime[0])
#c)
print("Month:", localTime[1])
#d)
print("Day of Week:", localTime.tm_wday, ",", weekDays[localTime.tm_wday])

#3)
past_time = current_time - timedelta(days=5)
print(past_time)
#4)
future_time = current_time + timedelta(days=5)
print(future_time)
